### ISSUE TITLE
Is there a reason why we can't browse as many directories as PS4FileNinja?

### ISSUE THREAD

**Issue by ghost** [Cryptogenic/PS4Console#4]
I'm looking at getting at some PS4 game files and I can't with the minimal access the script currently has. Is this even possible now on 3.55?

**Comment by Cryptogenic** [comment]
Yeah, PS4FileNinja is running on 1.76 where they've managed to break out of the jail that WebKit is in, in 3.55 we're still in this jail. So we can not view any files outside the FreeBSD Jail we're in at the moment, so our browsing capabilities and such are very limited until we break out of it.
